# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s="hi there sam!"
x=s.split()
print(x)

['hi', 'there', 'sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
planet ="Earth"
diameter=12742
y="the diameter of {planet} is {diameter}".format(planet="Earth",diameter="12742")
print(y)

the diameter of Earth is 12742


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [44]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [4]:
import numpy as np
b=np.zeros(10,dtype=int)
print("b:\n",b)

b:
 [0 0 0 0 0 0 0 0 0 0]


In [5]:
import numpy as np
b=np.ones(10)*5
print("b:\n",b)

b:
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [39]:
import numpy as np
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [6]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
mat=np.concatenate((a,b),axis=0)
print(mat)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [11]:
import pandas as pd
data=[['apple',10],['orange',22],['lemon',31]]
df=pd.DataFrame(data,columns=['fruits','amount'])
df

fruits  amount
0   apple      10
1  orange      22
2   lemon      31

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [37]:
import pandas as pd
a=pd.date_range(start='1-1-2023',end='10-2-2023',freq='2000H')
for value in a:
 print(a)



DatetimeIndex(['2023-01-01 00:00:00', '2023-03-25 08:00:00',
               '2023-06-16 16:00:00', '2023-09-08 00:00:00'],
              dtype='datetime64[ns]', freq='2000H')
DatetimeIndex(['2023-01-01 00:00:00', '2023-03-25 08:00:00',
               '2023-06-16 16:00:00', '2023-09-08 00:00:00'],
              dtype='datetime64[ns]', freq='2000H')
DatetimeIndex(['2023-01-01 00:00:00', '2023-03-25 08:00:00',
               '2023-06-16 16:00:00', '2023-09-08 00:00:00'],
              dtype='datetime64[ns]', freq='2000H')
DatetimeIndex(['2023-01-01 00:00:00', '2023-03-25 08:00:00',
               '2023-06-16 16:00:00', '2023-09-08 00:00:00'],
              dtype='datetime64[ns]', freq='2000H')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [38]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
data=(lists)
df=pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
