# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [26]:
s = "Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [29]:
planet = "Earth"
diameter = 12742
txt1="The diameter of {planet} is {diameter}".format(planet="Earth",diameter= "12742")
print(txt1)

The diameter of Earth is 12742


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [54]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [30]:
import numpy as np
b=np.zeros(10,dtype=int)
print("b: \n",b)


b: 
 [0 0 0 0 0 0 0 0 0 0]


In [31]:
import numpy as np
b=np.ones(10)*5
print("b: \n",b)

b: 
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [32]:
for x in range(20,35,2):
  print(x)

20
22
24
26
28
30
32
34


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [44]:
import numpy as np
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [38]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
matrix=np.concatenate((a,b),axis=0)
print(matrix)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [40]:
import pandas as pd
data=[{'R':2, 'S':3},{'R':10, 'S':20},{'R':4, 'S':28}]
data=pd.DataFrame(data,index=['first','second','third'])
print(data)

         R   S
first    2   3
second  10  20
third    4  28


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [41]:
import pandas as pd
a=pd.date_range(start='1-1-2023',end='10-2-2023',freq='2500H')
for value in a:
  print(a)

DatetimeIndex(['2023-01-01 00:00:00', '2023-04-15 04:00:00',
               '2023-07-28 08:00:00'],
              dtype='datetime64[ns]', freq='2500H')
DatetimeIndex(['2023-01-01 00:00:00', '2023-04-15 04:00:00',
               '2023-07-28 08:00:00'],
              dtype='datetime64[ns]', freq='2500H')
DatetimeIndex(['2023-01-01 00:00:00', '2023-04-15 04:00:00',
               '2023-07-28 08:00:00'],
              dtype='datetime64[ns]', freq='2500H')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [45]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
data=(lists)
df=pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
